// exercises/74-keyboard-reorder/exercise/src/App.tsx
import React, { useState } from "react";
        import { evaluate } from "./challenge";

        export function App() {
          const [input, setInput] = useState("");
          return <main><h1>Laboratório</h1><label htmlFor="case">Entrada</label><input id="case" value={input} onChange={e => setInput(e.target.value)} /><output aria-live="polite">{evaluate(input)}</output></main>;
        }

// exercises/73-accessible-combobox/solution/src/app.component.ts
import { Component } from "@angular/core";
        import { evaluate } from "./challenge";

        @Component({selector: "app-root", standalone: true, template: `<main><h1>Laboratório</h1><label for="case">Entrada</label><input id="case" #value (input)="output=evaluate(value.value)"><output aria-live="polite">{{output}}</output></main>`})
        export class AppComponent { output=""; evaluate=evaluate; }
