// exercises/120-accessible-chart-summary/exercise/src/app/App.tsx
import React, { useState } from "react"
        import { executeScenario } from "./public-api.ts"
        export function App() {
          const [input, setInput] = useState("")
          return <main><h1>Operations Console</h1><label htmlFor="scenario">Scenario input</label><input id="scenario" value={input} onChange={event => setInput(event.target.value)} /><output aria-live="polite">{executeScenario(input)}</output></main>
        }

// exercises/127-storage-quota-eviction/exercise/src/app/app.component.ts
import { Component } from "@angular/core"
        import { executeScenario } from "./public-api.ts"
        @Component({ selector: "app-root", standalone: true, template: `<main><h1>Operations Console</h1><label for="scenario">Scenario input</label><input id="scenario" #field (input)="output=execute(field.value)"><output aria-live="polite">{{output}}</output></main>` })
        export class AppComponent { output = ""; execute = executeScenario }
